export interface BlogPost {
  id: number
  slug: string
  category: string
  title: string
  date: string
  author: string
  image: string
}

export const blogPosts: BlogPost[] = [
  {
    id: 63,
    slug: "63",
    category: "결제·자금 관리",
    title: "사업자가 꼭 알아야 할 결제 방식별 세무 처리와 유의사항",
    date: "2025.10.15",
    author: "김정선 회계사",
    image: "/images/blog-thumbnail-1.png",
  },
  {
    id: 62,
    slug: "62",
    category: "결제·자금 관리",
    title: "사업자가 꼭 알아야 할 결제 방식별 세무 처리와 유의사항",
    date: "2025.10.12",
    author: "김정선 회계사",
    image: "/images/blog-thumbnail-2.png",
  },
  {
    id: 61,
    slug: "61",
    category: "결제·자금 관리",
    title: "사업자가 꼭 알아야 할 결제 방식별 세무 처리와 유의사항",
    date: "2025.10.10",
    author: "김정선 회계사",
    image: "/images/blog-thumbnail-3.png",
  },
  {
    id: 60,
    slug: "60",
    category: "결제·자금 관리",
    title: "사업자가 꼭 알아야 할 결제 방식별 세무 처리와 유의사항",
    date: "2025.10.08",
    author: "김정선 회계사",
    image: "/images/blog-thumbnail-4.png",
  },
  {
    id: 59,
    slug: "59",
    category: "세금",
    title: "직장인의 부업소득, 종합소득세 신고 대상일까요?",
    date: "2025.10.05",
    author: "김정선 회계사",
    image: "/images/blog-thumbnail-5.png",
  },
  {
    id: 58,
    slug: "58",
    category: "결제·자금 관리",
    title: "사업자가 꼭 알아야 할 결제 방식별 세무 처리와 유의사항",
    date: "2025.10.03",
    author: "김정선 회계사",
    image: "/images/blog-thumbnail-6.png",
  },
  {
    id: 57,
    slug: "57",
    category: "결제·자금 관리",
    title: "사업자가 꼭 알아야 할 결제 방식별 세무 처리와 유의사항",
    date: "2025.09.28",
    author: "김정선 회계사",
    image: "/images/blog-thumbnail-7.png",
  },
  {
    id: 56,
    slug: "56",
    category: "결제·자금 관리",
    title: "사업자가 꼭 알아야 할 결제 방식별 세무 처리와 유의사항",
    date: "2025.09.25",
    author: "김정선 회계사",
    image: "/images/blog-thumbnail-8.png",
  },
  {
    id: 55,
    slug: "55",
    category: "결제·자금 관리",
    title: "사업자가 꼭 알아야 할 결제 방식별 세무 처리와 유의사항",
    date: "2025.09.20",
    author: "김정선 회계사",
    image: "/images/blog-thumbnail-9.png",
  },

  {
    id: 54,
    slug: "54",
    category: "결제·자금 관리",
    title: "사업자가 꼭 알아야 할 결제 방식별 세무 처리와 유의사항",
    date: "2025.09.18",
    author: "김정선 회계사",
    image: "/images/blog-thumbnail-5.png",
  },
  {
    id: 53,
    slug: "53",
    category: "세금",
    title: "직장인의 부업소득, 종합소득세 신고 대상일까요?",
    date: "2025.09.15",
    author: "김정선 회계사",
    image: "/images/blog-thumbnail-2.png",
  },
  {
    id: 52,
    slug: "52",
    category: "결제·자금 관리",
    title: "사업자가 꼭 알아야 할 결제 방식별 세무 처리와 유의사항",
    date: "2025.09.12",
    author: "김정선 회계사",
    image: "/images/blog-thumbnail-8.png",
  },
  {
    id: 51,
    slug: "51",
    category: "결제·자금 관리",
    title: "사업자가 꼭 알아야 할 결제 방식별 세무 처리와 유의사항",
    date: "2025.09.10",
    author: "김정선 회계사",
    image: "/images/blog-thumbnail-4.png",
  },
  {
    id: 50,
    slug: "50",
    category: "결제·자금 관리",
    title: "사업자가 꼭 알아야 할 결제 방식별 세무 처리와 유의사항",
    date: "2025.09.08",
    author: "김정선 회계사",
    image: "/images/blog-thumbnail-7.png",
  },
  {
    id: 49,
    slug: "49",
    category: "결제·자금 관리",
    title: "사업자가 꼭 알아야 할 결제 방식별 세무 처리와 유의사항",
    date: "2025.09.05",
    author: "김정선 회계사",
    image: "/images/blog-thumbnail-6.png",
  },
  {
    id: 48,
    slug: "48",
    category: "결제·자금 관리",
    title: "사업자가 꼭 알아야 할 결제 방식별 세무 처리와 유의사항",
    date: "2025.09.03",
    author: "김정선 회계사",
    image: "/images/blog-thumbnail-1.png",
  },
  {
    id: 47,
    slug: "47",
    category: "결제·자금 관리",
    title: "사업자가 꼭 알아야 할 결제 방식별 세무 처리와 유의사항",
    date: "2025.08.30",
    author: "김정선 회계사",
    image: "/images/blog-thumbnail-3.png",
  },
  {
    id: 46,
    slug: "46",
    category: "결제·자금 관리",
    title: "사업자가 꼭 알아야 할 결제 방식별 세무 처리와 유의사항",
    date: "2025.08.28",
    author: "김정선 회계사",
    image: "/images/blog-thumbnail-9.png",
  },

  {
    id: 45,
    slug: "45",
    category: "결제·자금 관리",
    title: "사업자가 꼭 알아야 할 결제 방식별 세무 처리와 유의사항",
    date: "2025.08.25",
    author: "김정선 회계사",
    image: "/images/blog-thumbnail-7.png",
  },
  {
    id: 44,
    slug: "44",
    category: "결제·자금 관리",
    title: "사업자가 꼭 알아야 할 결제 방식별 세무 처리와 유의사항",
    date: "2025.08.22",
    author: "김정선 회계사",
    image: "/images/blog-thumbnail-4.png",
  },
  {
    id: 43,
    slug: "43",
    category: "세금",
    title: "직장인의 부업소득, 종합소득세 신고 대상일까요?",
    date: "2025.08.20",
    author: "김정선 회계사",
    image: "/images/blog-thumbnail-2.png",
  },
  {
    id: 42,
    slug: "42",
    category: "결제·자금 관리",
    title: "사업자가 꼭 알아야 할 결제 방식별 세무 처리와 유의사항",
    date: "2025.08.18",
    author: "김정선 회계사",
    image: "/images/blog-thumbnail-8.png",
  },
  {
    id: 41,
    slug: "41",
    category: "결제·자금 관리",
    title: "사업자가 꼭 알아야 할 결제 방식별 세무 처리와 유의사항",
    date: "2025.08.15",
    author: "김정선 회계사",
    image: "/images/blog-thumbnail-5.png",
  },
  {
    id: 40,
    slug: "40",
    category: "결제·자금 관리",
    title: "사업자가 꼭 알아야 할 결제 방식별 세무 처리와 유의사항",
    date: "2025.08.12",
    author: "김정선 회계사",
    image: "/images/blog-thumbnail-6.png",
  },
  {
    id: 39,
    slug: "39",
    category: "결제·자금 관리",
    title: "사업자가 꼭 알아야 할 결제 방식별 세무 처리와 유의사항",
    date: "2025.08.10",
    author: "김정선 회계사",
    image: "/images/blog-thumbnail-1.png",
  },
  {
    id: 38,
    slug: "38",
    category: "결제·자금 관리",
    title: "사업자가 꼭 알아야 할 결제 방식별 세무 처리와 유의사항",
    date: "2025.08.08",
    author: "김정선 회계사",
    image: "/images/blog-thumbnail-3.png",
  },
  {
    id: 37,
    slug: "37",
    category: "결제·자금 관리",
    title: "사업자가 꼭 알아야 할 결제 방식별 세무 처리와 유의사항",
    date: "2025.08.05",
    author: "김정선 회계사",
    image: "/images/blog-thumbnail-9.png",
  },

  {
    id: 36,
    slug: "36",
    category: "결제·자금 관리",
    title: "사업자가 꼭 알아야 할 결제 방식별 세무 처리와 유의사항",
    date: "2025.08.03",
    author: "김정선 회계사",
    image: "/images/blog-thumbnail-4.png",
  },
  {
    id: 35,
    slug: "35",
    category: "결제·자금 관리",
    title: "사업자가 꼭 알아야 할 결제 방식별 세무 처리와 유의사항",
    date: "2025.07.30",
    author: "김정선 회계사",
    image: "/images/blog-thumbnail-7.png",
  },
  {
    id: 34,
    slug: "34",
    category: "세금",
    title: "직장인의 부업소득, 종합소득세 신고 대상일까요?",
    date: "2025.07.28",
    author: "김정선 회계사",
    image: "/images/blog-thumbnail-2.png",
  },
  {
    id: 33,
    slug: "33",
    category: "결제·자금 관리",
    title: "사업자가 꼭 알아야 할 결제 방식별 세무 처리와 유의사항",
    date: "2025.07.25",
    author: "김정선 회계사",
    image: "/images/blog-thumbnail-8.png",
  },
  {
    id: 32,
    slug: "32",
    category: "결제·자금 관리",
    title: "사업자가 꼭 알아야 할 결제 방식별 세무 처리와 유의사항",
    date: "2025.07.22",
    author: "김정선 회계사",
    image: "/images/blog-thumbnail-5.png",
  },
  {
    id: 31,
    slug: "31",
    category: "결제·자금 관리",
    title: "사업자가 꼭 알아야 할 결제 방식별 세무 처리와 유의사항",
    date: "2025.07.20",
    author: "김정선 회계사",
    image: "/images/blog-thumbnail-6.png",
  },
  {
    id: 30,
    slug: "30",
    category: "결제·자금 관리",
    title: "사업자가 꼭 알아야 할 결제 방식별 세무 처리와 유의사항",
    date: "2025.07.18",
    author: "김정선 회계사",
    image: "/images/blog-thumbnail-1.png",
  },
  {
    id: 29,
    slug: "29",
    category: "결제·자금 관리",
    title: "사업자가 꼭 알아야 할 결제 방식별 세무 처리와 유의사항",
    date: "2025.07.15",
    author: "김정선 회계사",
    image: "/images/blog-thumbnail-3.png",
  },
  {
    id: 28,
    slug: "28",
    category: "결제·자금 관리",
    title: "사업자가 꼭 알아야 할 결제 방식별 세무 처리와 유의사항",
    date: "2025.07.12",
    author: "김정선 회계사",
    image: "/images/blog-thumbnail-9.png",
  },

  {
    id: 27,
    slug: "27",
    category: "결제·자금 관리",
    title: "사업자가 꼭 알아야 할 결제 방식별 세무 처리와 유의사항",
    date: "2025.07.10",
    author: "김정선 회계사",
    image: "/images/blog-thumbnail-9.png",
  },
  {
    id: 26,
    slug: "26",
    category: "결제·자금 관리",
    title: "사업자가 꼭 알아야 할 결제 방식별 세무 처리와 유의사항",
    date: "2025.07.08",
    author: "김정선 회계사",
    image: "/images/blog-thumbnail-6.png",
  },
  {
    id: 25,
    slug: "25",
    category: "세금",
    title: "직장인의 부업소득, 종합소득세 신고 대상일까요?",
    date: "2025.07.05",
    author: "김정선 회계사",
    image: "/images/blog-thumbnail-3.png",
  },
  {
    id: 24,
    slug: "24",
    category: "결제·자금 관리",
    title: "사업자가 꼭 알아야 할 결제 방식별 세무 처리와 유의사항",
    date: "2025.07.03",
    author: "김정선 회계사",
    image: "/images/blog-thumbnail-1.png",
  },
  {
    id: 23,
    slug: "23",
    category: "결제·자금 관리",
    title: "사업자가 꼭 알아야 할 결제 방식별 세무 처리와 유의사항",
    date: "2025.06.30",
    author: "김정선 회계사",
    image: "/images/blog-thumbnail-8.png",
  },
  {
    id: 22,
    slug: "22",
    category: "결제·자금 관리",
    title: "사업자가 꼭 알아야 할 결제 방식별 세무 처리와 유의사항",
    date: "2025.06.28",
    author: "김정선 회계사",
    image: "/images/blog-thumbnail-2.png",
  },
  {
    id: 21,
    slug: "21",
    category: "결제·자금 관리",
    title: "사업자가 꼭 알아야 할 결제 방식별 세무 처리와 유의사항",
    date: "2025.06.25",
    author: "김정선 회계사",
    image: "/images/blog-thumbnail-5.png",
  },
  {
    id: 20,
    slug: "20",
    category: "결제·자금 관리",
    title: "사업자가 꼭 알아야 할 결제 방식별 세무 처리와 유의사항",
    date: "2025.06.22",
    author: "김정선 회계사",
    image: "/images/blog-thumbnail-4.png",
  },
  {
    id: 19,
    slug: "19",
    category: "결제·자금 관리",
    title: "사업자가 꼭 알아야 할 결제 방식별 세무 처리와 유의사항",
    date: "2025.06.20",
    author: "김정선 회계사",
    image: "/images/blog-thumbnail-7.png",
  },

  {
    id: 18,
    slug: "18",
    category: "결제·자금 관리",
    title: "사업자가 꼭 알아야 할 결제 방식별 세무 처리와 유의사항",
    date: "2025.06.18",
    author: "김정선 회계사",
    image: "/images/blog-thumbnail-3.png",
  },
  {
    id: 17,
    slug: "17",
    category: "결제·자금 관리",
    title: "사업자가 꼭 알아야 할 결제 방식별 세무 처리와 유의사항",
    date: "2025.06.15",
    author: "김정선 회계사",
    image: "/images/blog-thumbnail-8.png",
  },
  {
    id: 16,
    slug: "16",
    category: "세금",
    title: "직장인의 부업소득, 종합소득세 신고 대상일까요?",
    date: "2025.06.12",
    author: "김정선 회계사",
    image: "/images/blog-thumbnail-5.png",
  },
  {
    id: 15,
    slug: "15",
    category: "결제·자금 관리",
    title: "사업자가 꼭 알아야 할 결제 방식별 세무 처리와 유의사항",
    date: "2025.06.10",
    author: "김정선 회계사",
    image: "/images/blog-thumbnail-2.png",
  },
  {
    id: 14,
    slug: "14",
    category: "결제·자금 관리",
    title: "사업자가 꼭 알아야 할 결제 방식별 세무 처리와 유의사항",
    date: "2025.06.08",
    author: "김정선 회계사",
    image: "/images/blog-thumbnail-9.png",
  },
  {
    id: 13,
    slug: "13",
    category: "결제·자금 관리",
    title: "사업자가 꼭 알아야 할 결제 방식별 세무 처리와 유의사항",
    date: "2025.06.05",
    author: "김정선 회계사",
    image: "/images/blog-thumbnail-1.png",
  },
  {
    id: 12,
    slug: "12",
    category: "결제·자금 관리",
    title: "사업자가 꼭 알아야 할 결제 방식별 세무 처리와 유의사항",
    date: "2025.06.03",
    author: "김정선 회계사",
    image: "/images/blog-thumbnail-6.png",
  },
  {
    id: 11,
    slug: "11",
    category: "결제·자금 관리",
    title: "사업자가 꼭 알아야 할 결제 방식별 세무 처리와 유의사항",
    date: "2025.05.30",
    author: "김정선 회계사",
    image: "/images/blog-thumbnail-4.png",
  },
  {
    id: 10,
    slug: "10",
    category: "결제·자금 관리",
    title: "사업자가 꼭 알아야 할 결제 방식별 세무 처리와 유의사항",
    date: "2025.05.28",
    author: "김정선 회계사",
    image: "/images/blog-thumbnail-7.png",
  },

  {
    id: 9,
    slug: "9",
    category: "결제·자금 관리",
    title: "사업자가 꼭 알아야 할 결제 방식별 세무 처리와 유의사항",
    date: "2025.05.25",
    author: "김정선 회계사",
    image: "/images/blog-thumbnail-6.png",
  },
  {
    id: 8,
    slug: "8",
    category: "결제·자금 관리",
    title: "사업자가 꼭 알아야 할 결제 방식별 세무 처리와 유의사항",
    date: "2025.05.22",
    author: "김정선 회계사",
    image: "/images/blog-thumbnail-1.png",
  },
  {
    id: 7,
    slug: "7",
    category: "세금",
    title: "직장인의 부업소득, 종합소득세 신고 대상일까요?",
    date: "2025.05.20",
    author: "김정선 회계사",
    image: "/images/blog-thumbnail-9.png",
  },
  {
    id: 6,
    slug: "6",
    category: "결제·자금 관리",
    title: "사업자가 꼭 알아야 할 결제 방식별 세무 처리와 유의사항",
    date: "2025.05.18",
    author: "김정선 회계사",
    image: "/images/blog-thumbnail-4.png",
  },
  {
    id: 5,
    slug: "5",
    category: "결제·자금 관리",
    title: "사업자가 꼭 알아야 할 결제 방식별 세무 처리와 유의사항",
    date: "2025.05.15",
    author: "김정선 회계사",
    image: "/images/blog-thumbnail-8.png",
  },
  {
    id: 4,
    slug: "4",
    category: "결제·자금 관리",
    title: "사업자가 꼭 알아야 할 결제 방식별 세무 처리와 유의사항",
    date: "2025.05.12",
    author: "김정선 회계사",
    image: "/images/blog-thumbnail-2.png",
  },
  {
    id: 3,
    slug: "3",
    category: "결제·자금 관리",
    title: "사업자가 꼭 알아야 할 결제 방식별 세무 처리와 유의사항",
    date: "2025.05.10",
    author: "김정선 회계사",
    image: "/images/blog-thumbnail-5.png",
  },
  {
    id: 2,
    slug: "2",
    category: "결제·자금 관리",
    title: "사업자가 꼭 알아야 할 결제 방식별 세무 처리와 유의사항",
    date: "2025.05.08",
    author: "김정선 회계사",
    image: "/images/blog-thumbnail-7.png",
  },
  {
    id: 1,
    slug: "1",
    category: "결제·자금 관리",
    title: "사업자가 꼭 알아야 할 결제 방식별 세무 처리와 유의사항",
    date: "2025.05.05",
    author: "김정선 회계사",
    image: "/images/blog-thumbnail-3.png",
  },
]
